# Generated by Django 2.2.12 on 2020-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200423_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='county',
            new_name='countries',
        ),
    ]
