# Generated by Django 2.2.12 on 2020-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='actor',
            name='imageSrc',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='posterSrc',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
