# Generated by Django 2.2.12 on 2020-04-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200424_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aboutSelf',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
