# Generated by Django 2.2.12 on 2020-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200426_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.IntegerField(),
        ),
    ]
